soma1 = input('Digite um primeiro número:')
soma2 = input('Digite o segundo número:')
soma1 = int(soma1)
soma2 = int(soma2)
igual = (soma1 + soma2)
print('A soma do primeiro + o segundo número é ',igual)